if(EXISTS "C:/Users/ebrus/Desktop/ce205-midterm-Ebru-Sener-YunusEmre-Yasar/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
  include("C:/Users/ebrus/Desktop/ce205-midterm-Ebru-Sener-YunusEmre-Yasar/build_win/src/tests/utility/utility_tests[1]_tests.cmake")
else()
  add_test(utility_tests_NOT_BUILT utility_tests_NOT_BUILT)
endif()
